// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagGGRue43N2gI6n1JxRfnjy8eiU90DzA',
    appId: '1:508248636536:web:d0e1acae995cba15a7818d',
    messagingSenderId: '508248636536',
    projectId: 'chatapp2-257ac',
    authDomain: 'chatapp2-257ac.firebaseapp.com',
    storageBucket: 'chatapp2-257ac.appspot.com',
    measurementId: 'G-FX882DTWMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNX89M_ruoa2JNiJzf7USzIlJtHC-TxPo',
    appId: '1:508248636536:android:a505c742cd966b13a7818d',
    messagingSenderId: '508248636536',
    projectId: 'chatapp2-257ac',
    storageBucket: 'chatapp2-257ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYItWgEoJ0WQQ9RaRo72NahmfBrToeW6w',
    appId: '1:508248636536:ios:bc42d3aaccbdbb2ba7818d',
    messagingSenderId: '508248636536',
    projectId: 'chatapp2-257ac',
    storageBucket: 'chatapp2-257ac.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYItWgEoJ0WQQ9RaRo72NahmfBrToeW6w',
    appId: '1:508248636536:ios:bc42d3aaccbdbb2ba7818d',
    messagingSenderId: '508248636536',
    projectId: 'chatapp2-257ac',
    storageBucket: 'chatapp2-257ac.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
